name: Deploy HTML with Docker

on: [push, pull_request]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh

      - name: Install Docker (If Not Installed)
        run: |
          if ! command -v docker &> /dev/null
          then
            echo "Installing Docker..."
            sudo apt update
            sudo apt install docker-ce docker-ce-cli containerd.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker already installed."
          fi

      - name: Build Docker Image
        run: |
          docker build -t my-html-site .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 --name html-container my-html-site
